name: mdbabel CI

on: [push, workflow_dispatch]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: cargo install --path .

      - name: Test (Dogfood)
        run: ~/.cargo/bin/mdbabel README.md
